
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[s_GetDebitCreditTotals]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[s_GetDebitCreditTotals]
GO

CREATE PROCEDURE [dbo].[s_GetDebitCreditTotals]		
		 @SystemDate DATE
		,@Result INT OUTPUT
AS
BEGIN
	WITH CURRENTTXN(ACCTNUM,SDTRAN_ID)
	 AS (
		SELECT 
			  ACCTNUM		 
			,MIN(SDTRAN_ID)
		FROM SDTRAN
		WHERE TRANDATE ='05/20/2016'
		GROUP BY ACCTNUM
		),
		OLDTXN(ACCTNUM,SDTRAN_ID)
	AS (
		SELECT 
			 ACCTNUM		
			,MAX(SDTRAN_ID)
		FROM SDTRAN
		WHERE ACCTNUM NOT  IN (SELECT ACCTNUM FROM CURRENTTXN)
		GROUP BY ACCTNUM
		)

END		
GO		
