
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[s_GetDebitCreditTotals]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[s_GetDebitCreditTotals]
GO

CREATE PROCEDURE [dbo].[s_GetDebitCreditTotals]		
		 @SystemDate DATE 
AS
BEGIN
	DECLARE
		 @CURRENTTOTALDEBIT AS DECIMAL(18,2)
		,@CURRENTTOTALCREDIT AS DECIMAL(18,2)
				
	select @CURRENTTOTALDEBIT=SUM(TRANDEB),@CURRENTTOTALCREDIT=SUM(TRANCRE) from SDTRAN where trandate=@SystemDate;
	
	WITH ALLTXN(ACCTNUM,SDTRAN_ID)
	 AS (
		SELECT 
			 ACCTNUM		 
			,MIN(SDTRAN_ID)
		FROM SDTRAN
		WHERE TRANDATE =@SystemDate
		GROUP BY ACCTNUM
		UNION ALL
		SELECT 
			 ACCTNUM		
			,MAX(SDTRAN_ID)			
		FROM SDTRAN
		WHERE ACCTNUM IS NOT NULL
		GROUP BY ACCTNUM
		HAVING MAX(TRANDATE) < @SystemDate		
		),
	CURRTXN(ACCTNUM,SDTRAN_ID)
	 AS (
		SELECT 
			 ACCTNUM		 
			,MIN(SDTRAN_ID)
		FROM SDTRAN
		WHERE TRANDATE =@SystemDate
		GROUP BY ACCTNUM	 
		)			
	SELECT 
		 SDTRAN_ID = 1 
		,'CURRENT TRANSACTIONS' ACCTNUM
		,SUM(CASE WHEN TRANDATE = @SystemDate 
			THEN A.TRANBBAL
			ELSE A.TRANEBAL END) TRANBBAL
		,@CURRENTTOTALDEBIT TRANDEB
		,@CURRENTTOTALCREDIT TRANCRE
		,(SUM(CASE WHEN TRANDATE = @SystemDate 
			THEN A.TRANBBAL
			ELSE A.TRANEBAL END) - @CURRENTTOTALDEBIT) + @CURRENTTOTALCREDIT TRANEBAL								
	from SDTRAN A
	WHERE EXISTS(SELECT SDTRAN_ID FROM CURRTXN B WHERE A.SDTRAN_ID = B.SDTRAN_ID)
	UNION ALL	
	SELECT 
		 SDTRAN_ID = 2
		,'ALL ACCOUNTS' ACCTNUM
		,SUM(CASE WHEN TRANDATE = @SystemDate 
			THEN A.TRANBBAL
			ELSE A.TRANEBAL END) TRANBBAL
		,@CURRENTTOTALDEBIT TRANDEB
		,@CURRENTTOTALCREDIT TRANCRE	
		,(SUM(CASE WHEN TRANDATE = @SystemDate 
			THEN A.TRANBBAL
			ELSE A.TRANEBAL END) - @CURRENTTOTALDEBIT) + @CURRENTTOTALCREDIT TRANEBAL						
	from SDTRAN A
	WHERE EXISTS(SELECT SDTRAN_ID FROM ALLTXN B WHERE A.SDTRAN_ID = B.SDTRAN_ID)	

END		
GO
--101000952
--101003552
--101040369
--101008910
--101054165
--101050631
--101050585
--101050348
--101007221
--101040369
--101050348

