DECLARE @TRANDEB AS MONEY DECLARE @TRANCRE AS MONEY DECLARE @TRANBBAL AS MONEY  
DECLARE @TRANEBAL AS MONEY DECLARE @CTRLNO AS CHAR(3)   

SELECT 
	 '001'
	,SUM(X.TRANBBAL)
	,SUM(X.TRANDEB)
	,SUM(X.TRANCRE)
	,SUM(X.TRANEBAL)
FROM 
	(SELECT 
	 A.ACCTNUM
	,(SELECT TRANBBAL FROM SDTRAN WHERE SDTRAN_ID= MIN(A.SDTRAN_ID)) TRANBBAL
	,SUM(A.TRANDEB) TRANDEB
	,SUM(A.TRANCRE) TRANCRE
	,(SELECT TRANEBAL FROM SDTRAN WHERE SDTRAN_ID= MAX(A.SDTRAN_ID)) TRANEBAL
	 FROM SDTRAN A INNER JOIN
	(SELECT ACCTNUM , MAX(TRANDATE) COMP FROM SDTRAN WITH (NOLOCK) GROUP BY ACCTNUM HAVING MAX(TRANDATE) IS NOT NULL) B
		ON A.ACCTNUM+CAST(A.TRANDATE AS VARCHAR(10))=B.ACCTNUM+CAST(B.COMP AS VARCHAR(10))
WHERE TRANDATE='03/27/2013'		
GROUP BY A.ACCTNUM) X  
SELECT @CTRLNO CTRLNO,@TRANBBAL TRANBBAL,@TRANDEB TRANDEB,@TRANCRE TRANCRE,@TRANEBAL TRANEBAL  
UNION ALL SELECT @CTRLNO CTRLNO ,SUM(Y.TRANBBAL) TRANBBAL	,@TRANDEB TRANDEB,@TRANCRE TRANCRE ,SUM(Y.TRANEBAL) TRANEBAL  
FROM (SELECT ACCTNUM,(SELECT TRANBBAL FROM SDTRAN WHERE SDTRAN_ID = MIN(ST.SDTRAN_ID))  
TRANBBAL,SUM(ST.TRANDEB) TRANDEB,SUM(ST.TRANCRE) TRANCRE,(SELECT TRANEBAL FROM SDTRAN WHERE SDTRAN_ID = MAX(ST.SDTRAN_ID)) TRANEBAL  
FROM SDTRAN ST  WITH (NOLOCK) GROUP BY ACCTNUM) Y


SELECT 
	 A.ACCTNUM
	,(SELECT TRANBBAL FROM SDTRAN WHERE SDTRAN_ID= MIN(A.SDTRAN_ID)) TRANBBAL
	,SUM(A.TRANDEB) TRANDEB
	,SUM(A.TRANCRE) TRANCRE
	,(SELECT TRANEBAL FROM SDTRAN WHERE SDTRAN_ID= MAX(A.SDTRAN_ID)) TRANEBAL
	 FROM SDTRAN A INNER JOIN
	(SELECT ACCTNUM , MAX(TRANDATE) COMP FROM SDTRAN WITH (NOLOCK) GROUP BY ACCTNUM HAVING MAX(TRANDATE) IS NOT NULL) B
		ON A.ACCTNUM+CAST(A.TRANDATE AS VARCHAR(10))=B.ACCTNUM+CAST(B.COMP AS VARCHAR(10))
WHERE TRANDATE='03/27/2013'		
GROUP BY A.ACCTNUM	