'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8669
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class GlobalResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SDS.Common.GlobalResource", GetType(GlobalResource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculating....
        '''</summary>
        Friend Shared ReadOnly Property Calculating() As String
            Get
                Return ResourceManager.GetString("Calculating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Password Failed!.
        '''</summary>
        Friend Shared ReadOnly Property ChangePasswordFailed() As String
            Get
                Return ResourceManager.GetString("ChangePasswordFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Password Successful!.
        '''</summary>
        Friend Shared ReadOnly Property ChangePasswordSuccess() As String
            Get
                Return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FOR THE DAY {0}.
        '''</summary>
        Friend Shared ReadOnly Property DebitCreditTotalsSubHeader() As String
            Get
                Return ResourceManager.GetString("DebitCreditTotalsSubHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DEBIT/CREDIT TOTALS.
        '''</summary>
        Friend Shared ReadOnly Property DebitCreditTotalsTitle() As String
            Get
                Return ResourceManager.GetString("DebitCreditTotalsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dividends / Refunds Import.
        '''</summary>
        Friend Shared ReadOnly Property DividendRefundImport() As String
            Get
                Return ResourceManager.GetString("DividendRefundImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dividend/Refund import successful. You can now execute DIV/REF posting..
        '''</summary>
        Friend Shared ReadOnly Property DivrefImportSuccess() As String
            Get
                Return ResourceManager.GetString("DivrefImportSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid date range please, select a valid date range..
        '''</summary>
        Friend Shared ReadOnly Property InvalidDateRange() As String
            Get
                Return ResourceManager.GetString("InvalidDateRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Records Found..
        '''</summary>
        Friend Shared ReadOnly Property NoRecordsFound() As String
            Get
                Return ResourceManager.GetString("NoRecordsFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ledger Recalculation.
        '''</summary>
        Friend Shared ReadOnly Property RecalculateLedger() As String
            Get
                Return ResourceManager.GetString("RecalculateLedger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recalculation Failed!.
        '''</summary>
        Friend Shared ReadOnly Property RecalculationFailed() As String
            Get
                Return ResourceManager.GetString("RecalculationFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recalculation Successful!.
        '''</summary>
        Friend Shared ReadOnly Property RecalculationSuccessful() As String
            Get
                Return ResourceManager.GetString("RecalculationSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Savings Deposit System.
        '''</summary>
        Friend Shared ReadOnly Property SavingsDepositSystem() As String
            Get
                Return ResourceManager.GetString("SavingsDepositSystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Savings Deposit System - Generate Report.
        '''</summary>
        Friend Shared ReadOnly Property SavingsDepositSystemReport() As String
            Get
                Return ResourceManager.GetString("SavingsDepositSystemReport", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
