/****** Object:  StoredProcedure [dbo].[Q_CTRL_S]    Script Date: 11/30/2011 19:42:40 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Q_CTRL_S]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Q_CTRL_S]
GO
CREATE PROCEDURE [dbo].[Q_CTRL_S]
   @f_Str as Varchar(255) = ''
 , @o_Str as Varchar(255) = ''
AS
BEGIN
DECLARE @q_Str as Varchar(1000)
SET NOCOUNT ON;
Set @q_Str = 'SELECT 
[CTRL_S_ID]
,[SYSDATE]
,[ADMDATE]
,[ADD_DATE]
,[CHG_DATE]
,[USER]
,[SDRATE]
,[ACCTBR]
,[ACCTSEQ]
,[PMAXL]
,[LMAXL]
,[BINIT]
,[BPOST]
,[CLR_ONUS]
,[CLR_LOCAL]
,[CLR_REG]
,[MINBAL]
,[DBDORMANT]
,[EOM_FLAG]
,[EOQ_FLAG]
,[EOY_FLAG]
,[OTC_FLAG]
,[EOD_FLAG]
,[P_PRINT]
,[R_PRINT]
FROM [CTRL_S] WITH (NOLOCK)'
EXEC(@q_Str + ' ' + @f_Str + ' ' + @o_Str)
END

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[U_CTRL_S]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[U_CTRL_S]
GO

/****** Object:  StoredProcedure [dbo].[U_CTRL_S]    Script Date: 11/30/2011 19:43:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[U_CTRL_S]
 @SYSDATE as DATETIME = NULL
,@ADMDATE as DATETIME = NULL
,@ADD_DATE as DATETIME = NULL
,@CHG_DATE as DATETIME = NULL
,@USER as VARCHAR(8) = NULL
,@SDRATE as NUMERIC(6,4) = NULL
,@ACCTBR as VARCHAR(4) = NULL
,@ACCTSEQ as NUMERIC(10,0) = NULL
,@PMAXL as NUMERIC(3,0) = NULL
,@LMAXL as NUMERIC(3,0) = NULL
,@BINIT as BIT = NULL
,@BPOST as BIT = NULL
,@CLR_ONUS as NUMERIC(2,0) = NULL
,@CLR_LOCAL as NUMERIC(2,0) = NULL
,@CLR_REG as NUMERIC(2,0) = NULL
,@MINBAL as NUMERIC(14,2) = NULL
,@DBDORMANT as NUMERIC(3,0) = NULL
,@EOM_FLAG as BIT = NULL
,@EOQ_FLAG as BIT = NULL
,@EOY_FLAG as BIT = NULL
,@OTC_FLAG as BIT = NULL
,@EOD_FLAG as BIT = NULL
,@P_PRINT as VARCHAR(4) = NULL
,@R_PRINT as VARCHAR(4) = NULL
,@CTRL_S_ID as VARCHAR = NULL
,@RESULT int OUTPUT
AS
BEGIN
SET NOCOUNT ON;
UPDATE [CTRL_S] SET 
 [SYSDATE] = ISNULL(@SYSDATE,[SYSDATE])
,[ADMDATE] = ISNULL(@ADMDATE,[ADMDATE])
,[ADD_DATE] = ISNULL(@ADD_DATE,[ADD_DATE])
,[CHG_DATE] = ISNULL(@CHG_DATE,[CHG_DATE])
,[USER] = ISNULL(@USER,[USER])
,[SDRATE] = ISNULL(@SDRATE,[SDRATE])
,[ACCTBR] = ISNULL(@ACCTBR,[ACCTBR])
,[ACCTSEQ] = ISNULL(@ACCTSEQ,[ACCTSEQ])
,[PMAXL] = ISNULL(@PMAXL,[PMAXL])
,[LMAXL] = ISNULL(@LMAXL,[LMAXL])
,[BINIT] = ISNULL(@BINIT,[BINIT])
,[BPOST] = ISNULL(@BPOST,[BPOST])
,[CLR_ONUS] = ISNULL(@CLR_ONUS,[CLR_ONUS])
,[CLR_LOCAL] = ISNULL(@CLR_LOCAL,[CLR_LOCAL])
,[CLR_REG] = ISNULL(@CLR_REG,[CLR_REG])
,[MINBAL] = ISNULL(@MINBAL,[MINBAL])
,[DBDORMANT] = ISNULL(@DBDORMANT,[DBDORMANT])
,[EOM_FLAG] = ISNULL(@EOM_FLAG,[EOM_FLAG])
,[EOQ_FLAG] = ISNULL(@EOQ_FLAG,[EOQ_FLAG])
,[EOY_FLAG] = ISNULL(@EOY_FLAG,[EOY_FLAG])
,[OTC_FLAG] = ISNULL(@OTC_FLAG,[OTC_FLAG])
,[EOD_FLAG] = ISNULL(@EOD_FLAG,[EOD_FLAG])
,[P_PRINT] = ISNULL(@P_PRINT,[P_PRINT])
,[R_PRINT] = ISNULL(@R_PRINT,[R_PRINT])
WHERE [CTRL_S_ID] = @CTRL_S_ID
SET @RESULT = @@ROWCOUNT
END

GO


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Q_SPUSER]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Q_SPUSER]
GO
CREATE PROCEDURE [dbo].[Q_SPUSER]
   @f_Str as Varchar(255) = ''
 , @o_Str as Varchar(255) = ''
AS
BEGIN
DECLARE @q_Str as Varchar(1000)
SET NOCOUNT ON;
Set @q_Str = 'SELECT 
[SPUSER_ID]
,[SPUSERID]
,[SPUSERPASS]
,[SPUSERNAME]
,[SPUSERPOS]
,[SPLOGSTAT]
,[SPLOGNO]
,[SPTELLER]
,[SPTAG]
,[CHG_DATE]
,[USER]
FROM [SPUSER] WITH (NOLOCK)'
EXEC(@q_Str + ' ' + @f_Str + ' ' + @o_Str)
END

GO


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[U_SPUSER]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[U_SPUSER]
GO
CREATE PROCEDURE [dbo].[U_SPUSER]
 @SPUSERID as VARCHAR(8) = NULL
,@SPUSERPASS as VARCHAR(8) = NULL
,@SPUSERNAME as VARCHAR(30) = NULL
,@SPUSERPOS as VARCHAR(1) = NULL
,@SPLOGSTAT as BIT = NULL
,@SPLOGNO as NUMERIC(3,0) = NULL
,@SPTELLER as BIT = NULL
,@SPTAG as VARCHAR(40) = NULL

,@USER as VARCHAR(8) = NULL
,@SPUSER_ID as BIGINT = NULL
,@RESULT int OUTPUT
AS
BEGIN
SET NOCOUNT ON;
UPDATE [SPUSER] SET 
 [SPUSERID] = ISNULL(@SPUSERID,[SPUSERID])
,[SPUSERPASS] = ISNULL(@SPUSERPASS,[SPUSERPASS])
,[SPUSERNAME] = ISNULL(@SPUSERNAME,[SPUSERNAME])
,[SPUSERPOS] = ISNULL(@SPUSERPOS,[SPUSERPOS])
,[SPLOGSTAT] = ISNULL(@SPLOGSTAT,[SPLOGSTAT])
,[SPLOGNO] = ISNULL(@SPLOGNO,[SPLOGNO])
,[SPTELLER] = ISNULL(@SPTELLER,[SPTELLER])
,[SPTAG] = ISNULL(@SPTAG,[SPTAG])
,[CHG_DATE] = GETDATE()
,[USER] = ISNULL(@USER,[USER])
WHERE [SPUSER_ID] = @SPUSER_ID
SET @RESULT = @@ROWCOUNT
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[I_SDOTHERS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[I_SDOTHERS]
GO
CREATE PROCEDURE [dbo].[I_SDOTHERS]
 @OTHDATE as DATETIME = NULL
,@OTHTIME as VARCHAR(8) = NULL
,@OTHNAME as VARCHAR(40) = NULL
,@OTHAMOUNT as NUMERIC(17,2) = NULL
,@OTHTYPE as VARCHAR(1) = NULL
,@OTHBANK as VARCHAR(10) = NULL
,@OTHCHKNO as VARCHAR(15) = NULL
,@OTHUSER as VARCHAR(8) = NULL
,@RESULT int OUTPUT
AS
BEGIN
SET NOCOUNT ON;
INSERT INTO [SDOTHERS] VALUES
(@OTHDATE
,@OTHTIME
,@OTHNAME
,@OTHAMOUNT
,@OTHTYPE
,@OTHBANK
,@OTHCHKNO
,@OTHUSER)
SET @RESULT = @@ROWCOUNT
END
GO

/****** Object:  StoredProcedure [dbo].[Q_SDOTHERS]    Script Date: 12/10/2011 17:49:45 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Q_SDOTHERS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Q_SDOTHERS]
GO


/****** Object:  StoredProcedure [dbo].[Q_SDOTHERS]    Script Date: 12/10/2011 17:49:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[Q_SDOTHERS]
   @f_Str as Varchar(255) = ''
 , @o_Str as Varchar(255) = ''
AS
BEGIN
DECLARE @q_Str as Varchar(1000)
SET NOCOUNT ON;
Set @q_Str = 'SELECT 
[SDOTHERS_ID]
,[OTHDATE]
,[OTHTIME]
,[OTHNAME]
,[OTHAMOUNT]
,[OTHTYPE]
,[OTHBANK]
,[OTHCHKNO]
,[OTHUSER]
FROM [SDOTHERS] WITH (NOLOCK)'
EXEC(@q_Str + ' ' + @f_Str + ' ' + @o_Str)
END


GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[U_SDOTHERS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[U_SDOTHERS]
GO
CREATE PROCEDURE [dbo].[U_SDOTHERS]
 @OTHDATE as VARCHAR(8) = NULL
,@OTHTIME as VARCHAR(8) = NULL
,@OTHNAME as VARCHAR(30) = NULL
,@OTHAMOUNT as VARCHAR(1) = NULL
,@OTHTYPE as BIT = NULL
,@OTHBANK as NUMERIC(3,0) = NULL
,@OTHCHKNO as BIT = NULL
,@OTHUSER as VARCHAR(40) = NULL
,@SDOTHERS_ID as BIGINT = NULL
,@RESULT int OUTPUT
AS
BEGIN
SET NOCOUNT ON;
UPDATE [SDOTHERS] SET 
 [OTHDATE] = ISNULL(@OTHDATE,[OTHDATE])
,[OTHTIME] = ISNULL(@OTHTIME,[OTHTIME])
,[OTHNAME] = ISNULL(@OTHNAME,[OTHNAME])
,[OTHAMOUNT] = ISNULL(@OTHAMOUNT,[OTHAMOUNT])
,[OTHTYPE] = ISNULL(@OTHTYPE,[OTHTYPE])
,[OTHBANK] = ISNULL(@OTHBANK,[OTHBANK])
,[OTHCHKNO] = ISNULL(@OTHCHKNO,[OTHCHKNO])
,[OTHUSER] = ISNULL(@OTHUSER,[OTHUSER])
WHERE [SDOTHERS_ID] = @SDOTHERS_ID
SET @RESULT = @@ROWCOUNT
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Q_SDMASTER]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Q_SDMASTER]
GO
CREATE PROCEDURE [dbo].[Q_SDMASTER]
   @f_Str as Varchar(255) = ''
 , @o_Str as Varchar(255) = ''
AS
BEGIN
DECLARE @q_Str as Varchar(1000)
SET NOCOUNT ON;
Set @q_Str = 'SELECT 
[SDMASTER_ID]
,[ACCTNO]
,[KBCI_NO]
,[CBEMPNO]
,[ACCTNAME]
,[ACCTADDR1]
,[ACCTADDR2]
,[ACCTSNAME]
,[ACCTPHONE1]
,[ACCTPHONE2]
,[ACCTDTYPE]
,[ACCTCCODE]
,[ACCTICODE]
,[ACCTATX]
,[ACCTOTH1]
,[ACCTOTH2]
,[ACCTMAINT]
,[ACCTIDEP]
,[ACCTPBAL]
,[ACCTLBAL]
,[ACCTOBAL]
,[ACCTABAL]
,[ACCTFLOATS]
,[ACCTTEX]
,[ACCTACLO]
,[ACCTWMIN]
,[ACCTWSC]
,[ACCTWINT]
,[ACCTSTAT]
,[PLINE]
,[LLINE]
,[UNPOSTED]
,[HOLDOUT]
,[LSEQ]
,[LTRANDATE]
,[ADD_DATE]
,[CHG_DATE]
,[UPD_USER]
,[REC_STAT]
FROM [SDMASTER] WITH (NOLOCK)'
EXEC(@q_Str + ' ' + @f_Str + ' ' + @o_Str)
END

GO
