Imports System.Windows.Forms

Public Class frmSDS_Main_Divref
    Private Sub frmSDS_Main_Divref_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        BackgroundWorker1.RunWorkerAsync()
    End Sub
    Sub PrcDIVREF(ByVal updVal As String)
        rExec("INSERT INTO SDTRAN(ACCTNUM,TRANDATE,TRANSEQ,TRANCODE,TRANBBAL,TRANDEB,TRANCRE,TRANEBAL,CHKNUM,CHKBANK,CHKCODE,ADD_DATE,ADD_TIME,[USER],OVERRIDE,PPOSTED,LPOSTED,TRANOLD,REVERSED) " & _
              "SELECT SM.ACCTNO,'" & CTRL_S.SYSDATE & "',CASE WHEN SM.LSEQ+1 < 1000 THEN SM.LSEQ+1 ELSE 1 END,'CM',SM.ACCTOBAL,0.00,DR." & updVal & ",SM.ACCTOBAL+DR." & updVal & "," & _
              "'" & updVal & "','','','" & CTRL_S.SYSDATE & "','" & Format(TimeOfDay, "HH:mm:ss") & "','" & SPUSER.SPUSERID & "','',0,0,0,0 FROM DIVREF DR INNER JOIN SDMASTER SM ON DR.FEBTC_SA=SM.ACCTNO LEFT JOIN MEMBERS MM ON SM.KBCI_NO = MM.KBCI_NO WHERE	DR." & updVal & " > 0  AND (MM.MEM_STAT='A' OR SM.ACCTNO='A')")
        rExec("UPDATE 	SDMASTER " & _
              "SET SDMASTER.LSEQ=SP.LSEQ,SDMASTER.ACCTOBAL=SP.ACCTOBAL,SDMASTER.ACCTABAL=SP.ACCTABAL, SDMASTER.ACCTLBAL=SP.ACCTLBAL " & _
              "FROM (SELECT SM.ACCTNO,SM.ACCTOBAL+DR." & updVal & " ACCTOBAL,SM.ACCTABAL+DR." & updVal & " ACCTABAL,SM.ACCTLBAL+DR." & updVal & " ACCTLBAL," & _
              "(CASE WHEN SM.LSEQ+1 < 1000 THEN SM.LSEQ+1 ELSE 1 END) LSEQ FROM DIVREF DR INNER JOIN SDMASTER SM ON DR.FEBTC_SA=SM.ACCTNO LEFT JOIN MEMBERS MM ON SM.KBCI_NO = MM.KBCI_NO " & _
              "WHERE DR." & updVal & " > 0  AND (MM.MEM_STAT='A' OR SM.ACCTNO='A')) AS SP WHERE SDMASTER.ACCTNO=SP.ACCTNO")
    End Sub

    Private Sub BackgroundWorker1_DoWork(ByVal sender As System.Object, ByVal e As System.ComponentModel.DoWorkEventArgs) Handles BackgroundWorker1.DoWork
        rExec("TRUNCATE TABLE DIVREF_S")
        rExec("INSERT INTO DIVREF_S(KBCI_NO,LNAME,FNAME,MI,FEBTC_SA,DIVIDEND,REFUND,DEDUCTIONS,SDTIME,SDBBAL,SDEBAL) " & _
              "SELECT DR.KBCI_NO,DR.LNAME,DR.FNAME,DR.MI,FEBTC_SA,DR.DIVIDEND,ISNULL(DR.REFUND,0),ISNULL(DR.DEDUCTIONS,0),'" & Format(TimeOfDay, "HH:mm:ss") & "',SM.ACCTOBAL,SM.ACCTOBAL+((DR.DIVIDEND+ISNULL(DR.REFUND,0))-ISNULL(DR.DEDUCTIONS,0)) " & _
              "FROM DIVREF DR INNER JOIN SDMASTER SM ON  DR.FEBTC_SA=SM.ACCTNO")
        PrcDIVREF("DIVIDEND")
        PrcDIVREF("REFUND")
        rExec("INSERT INTO SDTRAN(ACCTNUM,TRANDATE,TRANSEQ,TRANCODE,TRANBBAL,TRANDEB,TRANCRE,TRANEBAL,CHKNUM,CHKBANK,CHKCODE,ADD_DATE,ADD_TIME,[USER],OVERRIDE,PPOSTED,LPOSTED,TRANOLD,REVERSED) " & _
              "SELECT SM.ACCTNO,'" & CTRL_S.SYSDATE & "',CASE WHEN SM.LSEQ+1 < 1000 THEN SM.LSEQ+1 ELSE 1 END,'DM',SM.ACCTOBAL,DR.DEDUCTIONS,0.00,SM.ACCTOBAL-DR.DEDUCTIONS," & _
              "'DIV/REF HOLD','','','" & CTRL_S.SYSDATE & "','" & Format(TimeOfDay, "HH:mm:ss") & "','" & SPUSER.SPUSERID & "','',0,0,0,0 FROM DIVREF DR INNER JOIN SDMASTER SM ON DR.FEBTC_SA=SM.ACCTNO LEFT JOIN MEMBERS MM ON SM.KBCI_NO = MM.KBCI_NO WHERE	DR.DEDUCTIONS > 0  AND (MM.MEM_STAT='A' OR SM.ACCTNO='A')")
        rExec("UPDATE 	SDMASTER " & _
              "SET SDMASTER.LSEQ=SP.LSEQ,SDMASTER.ACCTOBAL=SP.ACCTOBAL,SDMASTER.ACCTABAL=SP.ACCTABAL, SDMASTER.ACCTLBAL=SP.ACCTLBAL " & _
              "FROM (SELECT SM.ACCTNO,SM.ACCTOBAL-DR.DEDUCTIONS ACCTOBAL,SM.ACCTABAL-DR.DEDUCTIONS ACCTABAL,SM.ACCTLBAL-DR.DEDUCTIONS ACCTLBAL," & _
              "(CASE WHEN SM.LSEQ+1 < 1000 THEN SM.LSEQ+1 ELSE 1 END) LSEQ FROM DIVREF DR INNER JOIN SDMASTER SM ON DR.FEBTC_SA=SM.ACCTNO LEFT JOIN MEMBERS MM ON MM.KBCI_NO=SM.KBCI_NO " & _
              "WHERE DR.DEDUCTIONS > 0 AND (MM.MEM_STAT='A' OR SM.ACCTNO='A')) AS SP WHERE SDMASTER.ACCTNO=SP.ACCTNO")
        rExec("UPDATE DIVREF_S SET DIVREF_S.SDSEQ=SM.LSEQ FROM (SELECT DR.FEBTC_SA,SM.LSEQ FROM DIVREF DR LEFT JOIN SDMASTER SM " & _
                  "ON DR.FEBTC_SA=SM.ACCTNO) SM WHERE(DIVREF_S.FEBTC_SA = SM.FEBTC_SA)")


    End Sub

    Private Sub BackgroundWorker1_RunWorkerCompleted(ByVal sender As System.Object, ByVal e As System.ComponentModel.RunWorkerCompletedEventArgs) Handles BackgroundWorker1.RunWorkerCompleted
        MsgBox("Processing Complete!")
        Me.Close()
    End Sub
End Class
